/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni.marisa.swig;

public final class NumTries {
  public final static NumTries MIN_NUM_TRIES = new NumTries("MIN_NUM_TRIES", marisaJNI.MIN_NUM_TRIES_get());
  public final static NumTries MAX_NUM_TRIES = new NumTries("MAX_NUM_TRIES", marisaJNI.MAX_NUM_TRIES_get());
  public final static NumTries DEFAULT_NUM_TRIES = new NumTries("DEFAULT_NUM_TRIES", marisaJNI.DEFAULT_NUM_TRIES_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NumTries swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NumTries.class + " with value " + swigValue);
  }

  private NumTries(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NumTries(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NumTries(String swigName, NumTries swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NumTries[] swigValues = { MIN_NUM_TRIES, MAX_NUM_TRIES, DEFAULT_NUM_TRIES };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

