/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni.marisa.swig;

public class Trie {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Trie(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Trie obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        marisaJNI.delete_Trie(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Trie() {
    this(marisaJNI.new_Trie(), true);
  }

  public void build(Keyset keyset, int config_flags) {
    marisaJNI.Trie_build__SWIG_0(swigCPtr, this, Keyset.getCPtr(keyset), keyset, config_flags);
  }

  public void build(Keyset keyset) {
    marisaJNI.Trie_build__SWIG_1(swigCPtr, this, Keyset.getCPtr(keyset), keyset);
  }

  public void mmap(String filename) {
    marisaJNI.Trie_mmap(swigCPtr, this, filename);
  }

  public void load(String filename) {
    marisaJNI.Trie_load(swigCPtr, this, filename);
  }

  public void save(String filename) {
    marisaJNI.Trie_save(swigCPtr, this, filename);
  }

  public boolean lookup(Agent agent) {
    return marisaJNI.Trie_lookup__SWIG_0(swigCPtr, this, Agent.getCPtr(agent), agent);
  }

  public void reverse_lookup(Agent agent) {
    marisaJNI.Trie_reverse_lookup__SWIG_0(swigCPtr, this, Agent.getCPtr(agent), agent);
  }

  public boolean common_prefix_search(Agent agent) {
    return marisaJNI.Trie_common_prefix_search(swigCPtr, this, Agent.getCPtr(agent), agent);
  }

  public boolean predictive_search(Agent agent) {
    return marisaJNI.Trie_predictive_search(swigCPtr, this, Agent.getCPtr(agent), agent);
  }

  public long lookup(byte[] ptr) {
    return marisaJNI.Trie_lookup__SWIG_1(swigCPtr, this, ptr);
  }

  public String reverse_lookup(long id) {
    return marisaJNI.Trie_reverse_lookup__SWIG_1(swigCPtr, this, id);
  }

  public long num_tries() {
    return marisaJNI.Trie_num_tries(swigCPtr, this);
  }

  public long num_keys() {
    return marisaJNI.Trie_num_keys(swigCPtr, this);
  }

  public long num_nodes() {
    return marisaJNI.Trie_num_nodes(swigCPtr, this);
  }

  public TailMode tail_mode() {
    return TailMode.swigToEnum(marisaJNI.Trie_tail_mode(swigCPtr, this));
  }

  public NodeOrder node_order() {
    return NodeOrder.swigToEnum(marisaJNI.Trie_node_order(swigCPtr, this));
  }

  public boolean empty() {
    return marisaJNI.Trie_empty(swigCPtr, this);
  }

  public long size() {
    return marisaJNI.Trie_size(swigCPtr, this);
  }

  public long total_size() {
    return marisaJNI.Trie_total_size(swigCPtr, this);
  }

  public long io_size() {
    return marisaJNI.Trie_io_size(swigCPtr, this);
  }

  public void clear() {
    marisaJNI.Trie_clear(swigCPtr, this);
  }

}
