/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni.marisa.swig;

public final class CacheLevel {
  public final static CacheLevel HUGE_CACHE = new CacheLevel("HUGE_CACHE", marisaJNI.HUGE_CACHE_get());
  public final static CacheLevel LARGE_CACHE = new CacheLevel("LARGE_CACHE", marisaJNI.LARGE_CACHE_get());
  public final static CacheLevel NORMAL_CACHE = new CacheLevel("NORMAL_CACHE", marisaJNI.NORMAL_CACHE_get());
  public final static CacheLevel SMALL_CACHE = new CacheLevel("SMALL_CACHE", marisaJNI.SMALL_CACHE_get());
  public final static CacheLevel TINY_CACHE = new CacheLevel("TINY_CACHE", marisaJNI.TINY_CACHE_get());
  public final static CacheLevel DEFAULT_CACHE = new CacheLevel("DEFAULT_CACHE", marisaJNI.DEFAULT_CACHE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CacheLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CacheLevel.class + " with value " + swigValue);
  }

  private CacheLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CacheLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CacheLevel(String swigName, CacheLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CacheLevel[] swigValues = { HUGE_CACHE, LARGE_CACHE, NORMAL_CACHE, SMALL_CACHE, TINY_CACHE, DEFAULT_CACHE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

