/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni.marisa.swig;

public class Keyset {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Keyset(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Keyset obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        marisaJNI.delete_Keyset(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Keyset() {
    this(marisaJNI.new_Keyset(), true);
  }

  public void push_back(byte[] ptr, float weight) {
    marisaJNI.Keyset_push_back__SWIG_0(swigCPtr, this, ptr, weight);
  }

  public void push_back(byte[] ptr) {
    marisaJNI.Keyset_push_back__SWIG_1(swigCPtr, this, ptr);
  }

  public Key key(long i) {
    return new Key(marisaJNI.Keyset_key(swigCPtr, this, i), false);
  }

  public String key_str(long i) {
    return marisaJNI.Keyset_key_str(swigCPtr, this, i);
  }

  public long key_id(long i) {
    return marisaJNI.Keyset_key_id(swigCPtr, this, i);
  }

  public long num_keys() {
    return marisaJNI.Keyset_num_keys(swigCPtr, this);
  }

  public boolean empty() {
    return marisaJNI.Keyset_empty(swigCPtr, this);
  }

  public long size() {
    return marisaJNI.Keyset_size(swigCPtr, this);
  }

  public long total_length() {
    return marisaJNI.Keyset_total_length(swigCPtr, this);
  }

  public void reset() {
    marisaJNI.Keyset_reset(swigCPtr, this);
  }

  public void clear() {
    marisaJNI.Keyset_clear(swigCPtr, this);
  }

}
