/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni.marisa.swig;

public final class NodeOrder {
  public final static NodeOrder LABEL_ORDER = new NodeOrder("LABEL_ORDER", marisaJNI.LABEL_ORDER_get());
  public final static NodeOrder WEIGHT_ORDER = new NodeOrder("WEIGHT_ORDER", marisaJNI.WEIGHT_ORDER_get());
  public final static NodeOrder DEFAULT_ORDER = new NodeOrder("DEFAULT_ORDER", marisaJNI.DEFAULT_ORDER_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NodeOrder swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NodeOrder.class + " with value " + swigValue);
  }

  private NodeOrder(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NodeOrder(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NodeOrder(String swigName, NodeOrder swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NodeOrder[] swigValues = { LABEL_ORDER, WEIGHT_ORDER, DEFAULT_ORDER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

